# Generated by Django 6.0.2 on 2026-06-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
